CREATE TABLE financeiro
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor      DECIMAL(10, 2)                          NOT NULL,
    descricao  VARCHAR(255)          NOT NULL,
    recdesp    INTEGER                                 NOT NULL,
    categoria  VARCHAR(255)                            NOT NULL,
    necessario VARCHAR(255),
    usuario_id BIGINT                                  NOT NULL,
    data       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_financeiro PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    nome      VARCHAR(255)                            NOT NULL,
    senha     VARCHAR(255),
    criado_em TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_email UNIQUE (email);

ALTER TABLE financeiro
    ADD CONSTRAINT FK_FINANCEIRO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);

-- Inserir usuários de teste
INSERT INTO usuario (nome, email, senha) VALUES
    ('João Silva', 'joao@email.com', 'senha123hash'),
    ('Maria Santos', 'maria@email.com', 'senha456hash'),
    ('Pedro Costa', 'pedro@email.com', 'senha789hash');

-- Inserir despesas de teste para João (id = 1)
-- recdesp: -1 = despesa, 1 = receita
INSERT INTO financeiro (descricao, valor, recdesp, categoria, necessario, data, usuario_id) VALUES
('Compra no mercado', 250.00, -1, 'ALIMENTACAO', 'SIM', '2026-04-01 10:30:00', 1),
('Passagem de ônibus', 8.00, -1, 'TRANSPORTE', 'SIM', '2026-04-01 08:00:00', 1),
('Consulta médica', 150.00, -1, 'SAUDE', 'SIM', '2026-04-02 14:00:00', 1),
('Cinema', 60.00, -1, 'LAZER', 'NAO', '2026-04-03 19:00:00', 1),
('Mercado novamente', 320.00, -1, 'ALIMENTACAO', 'SIM', '2026-04-05 15:30:00', 1),
('Combustível', 200.00, -1, 'TRANSPORTE', 'SIM', '2026-04-05 16:00:00', 1),
('Academia', 100.00, -1, 'SAUDE', 'SIM', '2026-04-06 07:00:00', 1),
('Compras de roupas', 450.00, -1, 'OUTROS', 'NAO', '2026-04-07 14:00:00', 1);

INSERT INTO financeiro (descricao, valor, recdesp, categoria, necessario, data, usuario_id) VALUES
('Compra no mercado', 250.00, -1, 'ALIMENTACAO', 'SIM', '2026-03-01 10:30:00', 1),
('Passagem de ônibus', 8.00, -1, 'TRANSPORTE', 'SIM', '2026-03-01 08:00:00', 1),
('Consulta médica', 120.00, -1, 'SAUDE', 'SIM', '2026-03-02 14:00:00', 1),
('Cinema', 30.00, -1, 'LAZER', 'NAO', '2026-03-03 19:00:00', 1),
('Mercado novamente', 180.00, -1, 'ALIMENTACAO', 'SIM', '2026-03-05 15:30:00', 1),
('Combustível', 400.00, -1, 'TRANSPORTE', 'SIM', '2026-03-05 16:00:00', 1),
('Academia', 100.00, -1, 'SAUDE', 'SIM', '2026-03-06 07:00:00', 1),
('Compras de roupas', 200.00, -1, 'OUTROS', 'NAO', '2026-03-07 14:00:00', 1);

-- Inserir despesas de teste para Maria (id = 2)
INSERT INTO financeiro (descricao, valor, recdesp, categoria, necessario, data, usuario_id) VALUES
('Supermercado', 180.00, -1, 'ALIMENTACAO', 'SIM', '2026-04-01 12:00:00', 2),
('Uber', 35.00, -1, 'TRANSPORTE', 'NAO', '2026-04-02 18:30:00', 2),
('Restaurante', 120.00, -1, 'ALIMENTACAO', 'NAO', '2024-04-04 20:00:00', 2);

-- Inserir despesas de teste para Pedro (id = 3)
INSERT INTO financeiro (descricao, valor, recdesp, categoria, necessario, data, usuario_id) VALUES
('Aluguel', 1500.00, -1, 'MORADIA', 'SIM', '2026-04-01 09:00:00', 3),
('Conta de água', 120.00, -1, 'UTILIDADES', 'SIM', '2026-04-05 10:00:00', 3);